language: swift
osx_image: xcode9.2
install:
  - bundle install
  - bundle update
  - pod update --project-directory=/Users/travis/build/Thornaci/Steem-Tracker/
script:
  - fastlane runTests
after_success:
  - cd $TRAVIS_BUILD_DIR && slather
xcode_project: SteemitApp.xcode_workspace
xcode_scheme: SteemitApp
os: osx