setup_travis
fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  	lane :pushToSprint do

  	  	version = get_version_number()
    	git_tag = "Version-" + version
    	add_git_tag(tag: git_tag)

    	git_add
    	commit_version_bump(message: 'These files pushed via Fastlane for PO', force: true)

  		push_to_git_remote(remote: 'origin', 
      		local_branch: 'dev', 
      		remote_branch: 'sprint'
      	)  
  	end

	lane :pushToDev do

    	increment_build_number

    	commit_version_bump(message: 'These files pushed via Fastlane for Tester', force: true)

    	push_to_git_remote(remote: 'origin', 
      		local_branch: 'dev', 
      		remote_branch: 'dev'
      	)   
    end  

    lane :runTests do
    	scan(scheme: "SteemitApp", code_coverage: true, device: "iPhone 6")
    	# slather(travis: true, coveralls: true, scheme: "SteemitApp", workspace: "./SteemitApp.xcworkspace", proj: "./SteemitApp.xcodeproj", cobertura_xml: true)
    end 
end

