fastlane_version "2.64.1"

default_platform :ios

platform :ios do
  lane :push do
    # increment_build_number
    # build = get_build_number()
    # version = get_version_number()

    # git_tag = "Version-" + version + "." + build
    # add_git_tag(tag: git_tag)
    git_add
    commit_version_bump(message: 'This files pushed via Fastlane', force: true)

    push_to_git_remote(
      remote: 'origin', 
      # local_branch: 'master', 
      # remote_branch: 'master'
    )
  end
end

